name: Build and deploy Python app to Azure Web App - prmapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prmapi'
          slot-name: 'Production'
          package: ./backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6B8498DC7BA141E9949F9B638627E23A }}
